### ISSUE TITLE
Python 3.4 support

### ISSUE THREAD

**Issue by StyleEX** [markfinger/django-node#3]
I try using this module on python 3.4, but i receive this error:

    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/styleex/ferrario/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/home/styleex/ferrario/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
        django.setup()
      File "/home/styleex/ferrario/env/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/home/styleex/ferrario/env/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
        app_config = AppConfig.create(entry)
      File "/home/styleex/ferrario/env/lib/python3.4/site-packages/django/apps/config.py", line 87, in create
        module = import_module(entry)
      File "/home/styleex/ferrario/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1448, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/home/styleex/ferrario/env/lib/python3.4/site-packages/django_react/__init__.py", line 1, in <module>
        from .components import ReactComponent
      File "/home/styleex/ferrario/env/lib/python3.4/site-packages/django_react/components.py", line 10, in <module>
        from .render import render_component
      File "/home/styleex/ferrario/env/lib/python3.4/site-packages/django_react/render.py", line 4, in <module>
        from django_node import npm, node
      File "/home/styleex/ferrario/env/lib/python3.4/site-packages/django_node/npm.py", line 2, in <module>
        import settings
    ImportError: No module named 'settings'

**Comment by markfinger** [comment]
Thanks for reporting the issue. This has been fixed and django-react 0.9.0 should now work with Python 3.4.

One caveat to be aware of is that one of django-webpack's dependencies (which are resolved the first time the package is run) requires Python 2.x during the installation process. With Python 3, NPM will still complete the installation of the packages and the system appears to function as expected, but a bunch of errors will be spewed out to the terminal when you first try to import django-react.

You can fix this by adding a path to a Python 2 interpreter to your settings...

```python
DJANGO_NODE = {
    'NPM_INSTALL_PATH_TO_PYTHON': '/path/to/python2',
}
```

Cheers,
Mark
